package frc.robot.Subsytems.Swerve;

import static edu.wpi.first.units.Units.*;

import java.io.IOException;
import java.lang.annotation.Retention;
import java.util.Optional;
import java.util.function.BooleanSupplier;
import java.util.function.Supplier;

import org.json.simple.parser.ParseException;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathPlannerPath;
import com.pathplanner.lib.pathfinding.Pathfinder;
import com.pathplanner.lib.util.FileVersionException;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructArrayPublisher;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.RunCommand;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.WaitCommand;
import edu.wpi.first.wpilibj2.command.WaitUntilCommand;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants.TelemetryConstants;
import frc.robot.Constants.States.SwerveStates.SwerveState;
import frc.robot.Constants.Dimensions;
import frc.robot.Constants.DriveConstants;
import frc.robot.Constants.PoseConstants;
import frc.robot.Constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.Subsytems.Swerve.Commands.SwerveAimToHub;
import frc.robot.Subsytems.Swerve.Commands.SwerveGetIntoShootAreaCommand;
import frc.robot.Subsytems.Swerve.Commands.SwerveTeleopCommand;
import frc.robot.Subsytems.Swerve.Utils.SwerveControlData;
import frc.robot.Utils.SwerveFieldContactSim;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.001; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private Pigeon2 imu;
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private SwerveControlData swerveData = new SwerveControlData();


    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        imu = new Pigeon2(drivetrainConstants.Pigeon2Id);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();

        setStartPose1();
    }


    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        setStartPose1();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        if (TelemetryConstants.SHOULD_SWERVE_DATA_COMMUNICATE) {
            SmartDashboard.putData("Swerve Control Data", swerveData);
        }

        if (TelemetryConstants.SHOULD_SWERVE_FIELD_COMMUNICATE) {
            SmartDashboard.putData("Field", swerveData.field);
        }

        if (DriverStation.getAlliance().get() == Alliance.Red) {
            swerveData.distanceToHub = Meters.of(PoseConstants.RED_HUB_AIM_POSE.getTranslation().getDistance(getPose().getTranslation()));
        } else {
            swerveData.distanceToHub = Meters.of(PoseConstants.BLUE_HUB_AIM_POSE.getTranslation().getDistance(getPose().getTranslation()));
        }

    }

    public void updateSwerveData(){
        
        swerveData.robotPose = getState().Pose;
        swerveData.field.setRobotPose(swerveData.robotPose);

        swerveData.robotVelocityX = MetersPerSecond.of(getState().Speeds.vxMetersPerSecond);
        swerveData.robotVelocityY = MetersPerSecond.of(getState().Speeds.vyMetersPerSecond);
        swerveData.robotSpeed =  MetersPerSecond.of(
            Math.hypot(getState().Speeds.vxMetersPerSecond, getState().Speeds.vyMetersPerSecond));
        swerveData.robotAngularVelocity = RadiansPerSecond.of(getState().Speeds.omegaRadiansPerSecond);
    }

    public void updateSwerveErrors(
        Pose2d desiredPose
    ){
        swerveData.robotXError = Meters.of(desiredPose.getX() - swerveData.robotPose.getX());
        swerveData.robotYError = Meters.of(desiredPose.getY() - swerveData.robotPose.getY());
        swerveData.robotAngleError = Degrees.of(
            desiredPose.getRotation().minus(swerveData.robotPose.getRotation()).getDegrees()
        );
    }

    public SwerveState getSwerveState() {
        return swerveData.swerveControlState;
    }

    public void setSwerveState(SwerveState state) {
        swerveData.swerveControlState = state;
    }

    public Supplier<SwerveControlData> swerveDataSupplier()
    {
        return (() -> {return swerveData;});
    }

    public StatusSignal<Angle> getHeadingStatusSignalType(){
        return imu.getYaw();
    }

    public Pose2d getPose() {
        return getState().Pose;
    }

    public ChassisSpeeds getFieldSpeeds() {
        return getState().Speeds;
    }
    

    public double getGyroHeading() {
        double rawYaw = getHeadingStatusSignalType().getValueAsDouble();
        double yawWrapped = rawYaw % 360;
        if (yawWrapped < 0){
            yawWrapped += 360;
        }
        return yawWrapped;
    }

    public void gyroReset() {
        this.seedFieldCentric();
        imu.reset();
    }

    public PIDController getAimingPID(){
        return swerveData.aimingPID;
    }

    public StructPublisher<Pose2d> posePublisher = NetworkTableInstance.getDefault()
            .getStructTopic("Sim/SwervePose", Pose2d.struct)
            .publish();

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;
            posePublisher.set(getState().Pose);
            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    private boolean isSimulationInitialized = false;
    
    @Override
    public void simulationPeriodic() {

        if(!isSimulationInitialized)
        {
            m_lastSimTime = Utils.getCurrentTimeSeconds();
            isSimulationInitialized = true;
            return;
        }

        final double currentTime = Utils.getCurrentTimeSeconds();
        double deltaTime = currentTime - m_lastSimTime;
        m_lastSimTime = currentTime;
        posePublisher.set(getState().Pose);
        /* use the measured time delta, get battery voltage from WPILib */
        updateSimState(deltaTime, RobotController.getBatteryVoltage());
        SwerveFieldContactSim.getInstance().handleSwerveSimFieldCollisions();
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> {return false;},
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }


    
    public Command teleopCommand(CommandXboxController driverController) {
        return new SwerveTeleopCommand(this, driverController);
    }

    public Command aimToHub() {
        return new SwerveAimToHub(this);
    }

    public Command getIntoShootArea() {
        return new SwerveGetIntoShootAreaCommand(this);
    }

    public Command goToPose(Pose2d targetPose) {
        return AutoBuilder.pathfindToPose(targetPose, DriveConstants.PATH_CONSTRAINTS_TO_POSE).deadlineFor(new RunCommand(() -> {
          updateSwerveErrors(targetPose);
          setSwerveState(SwerveState.PATH_FOLLOWING);
        }));
    }

    public Command followPath(PathPlannerPath path) {

        final PathPlannerPath pathToFollow;

        if (DriverStation.getAlliance().get() == DriverStation.Alliance.Red){
            pathToFollow = path.flipPath();
        } else {
            pathToFollow = path;
        }
        
        return AutoBuilder.followPath(pathToFollow).deadlineFor(new RunCommand(() -> {
          updateSwerveErrors(pathToFollow.getPathPoses().get(pathToFollow.getPathPoses().size() - 1));
          setSwerveState(SwerveState.PATH_FOLLOWING);
        }));
    }

    public Command pathfindThenFollowPath(PathPlannerPath path) {

        final PathPlannerPath pathToFollow;

        if (DriverStation.getAlliance().get() == DriverStation.Alliance.Red){
            pathToFollow = path.flipPath();
        }
        else{
            pathToFollow = path;
        }

        return AutoBuilder.pathfindThenFollowPath(pathToFollow, DriveConstants.PATH_CONSTRAINTS_TO_POSE).deadlineFor(new RunCommand(() -> {
          updateSwerveErrors(pathToFollow.getPathPoses().get(pathToFollow.getPathPoses().size() - 1));
          setSwerveState(SwerveState.PATH_FOLLOWING);
        }));
    }

    public void setStartPose1()
    {
        if(DriverStation.getAlliance().get() == DriverStation.Alliance.Red){
            resetPose(PoseConstants.START_POSE_RED_1);
        }
        else{
            resetPose(PoseConstants.START_POSE_BLUE_1);
        }
    }

    public InstantCommand resetToStartPoseCmd()
    {
        return new InstantCommand(() -> setStartPose1());
    }

    public void setIsAimed(boolean isAimed)
    {
        swerveData.isAimed = isAimed;
    }

    public Command waitForAtAim()
    {
        return new WaitUntilCommand(() -> {return swerveData.isAimed;});
    }

    public Command pathFindToIntakeWall()
    {
        Pose2d targetPose = new Pose2d(-1, -1, Rotation2d.fromDegrees(-1));

        try {
            targetPose = PathPlannerPath.fromPathFile("WallIntake").getPathPoses().get(0);

        } catch (FileVersionException | IOException | ParseException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }

        return goToPose(targetPose);
    }

    public Command pathFindToTrench1()
    {
        Pose2d targetPose = new Pose2d(-1, -1, Rotation2d.fromDegrees(-1));

        try {
            targetPose = PathPlannerPath.fromPathFile("TrenchIntake1").getPathPoses().get(0);
        } catch (FileVersionException | IOException | ParseException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }

        return goToPose(targetPose);
    }

    public InstantCommand setStartPose1Command()
    {
        return new InstantCommand(() -> setStartPose1());
    }

    public Command followPathIntakeWall()
    {
        PathPlannerPath path = null;

        try {
            path = PathPlannerPath.fromPathFile("IntakeWall");
        } catch (FileVersionException | IOException | ParseException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }

        return pathfindThenFollowPath(path);
    }

     public Command followPathTrench1()
    {
        PathPlannerPath path = null;

        try {
            path = PathPlannerPath.fromPathFile("TrenchIntake1");
        } catch (FileVersionException | IOException | ParseException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }

        return pathfindThenFollowPath(path);
     }
}